<?php

use Application\Entity\User;

/**
 * 
 * @var User $user
 */
$user = $this->user;

?>
<div class="col-md-6 col-md-offset-3">
	<div class="row">
		<h2>Wijzig wachtwoord</h2>
		
		<hr>
	
	</div>

	<form action="/admin/user/changepassword/<?php echo $user->getId() ?>" method="post">
		
		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
					<label for="username" class="control-label">Gebruikersnaam</label>
                    <input type="text" name="username" id="username" class="form-control" value="<?php echo $user->getUsername() ?>" disabled>
                </div>
        	</div>
        </div>
		
		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
					<label for="password" class="control-label">Wachtwoord</label>
					<div class="input-group">
                        <input type="password" name="password" id="password" class="form-control" required>
                        <div class="input-group-addon">
                        	<span id="hideShowPassword" class="glyphicon glyphicon-eye-open"></span>
                        </div>
                    </div>
                </div>
        	</div>
		</div>

		<div class="form-group">
			<button class="btn btn-primary">Opslaan</button>
		</div>
		
	</form>
</div>
