<?php

use Application\Entity\User;
use Application\Entity\Url;

/**
 * 
 * @var User $user
 */
$user = $this->user;

?>

<div class="col-md-6 col-md-offset-3">
	<div class="row">
		<h2>Wijzig gebruiker</h2>
		
		<hr>
	
	</div>

	<form action="/admin/user/edit/<?php echo $user->getId() ?>" method="post">
		
		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
					<label for="username" class="control-label">Gebruikersnaam</label>
                    <input type="text" name="username" id="username" class="form-control" value="<?php echo $user->getUsername() ?>" required>
                </div>
        	</div>
        </div>
		
		<div class="row">
			<div class="col-md-10">
				<div class="form-group">
					<label for="displayName" class="control-label">Volledige naam</label>
                    <input type="text" name="displayName" id="displayName" class="form-control" value="<?php echo $user->getDisplayName() ?>" required>
                </div>
        	</div>
        </div>
		
		<div class="row">
			<div class="col-md-10">
				<div class="form-group">
					<label for="email" class="control-label">E-mail adres</label>
                    <input type="text" name="email" id="email" class="form-control" value="<?php echo $user->getEmail() ?>" required>
                </div>
        	</div>
        </div>

		<div class="row">
			<div class="col-md-10">
				<div class="form-group">
					<label for="apikey" class="control-label">API key</label>
                    <input type="text" name="apikey" id="apikey" class="form-control" value="<?php echo $user->getApikey() ?>" required>
                    
                </div>
        	</div>
        	<div class="col-md-2">
        		<div class="form-group">
        			<label class="control-label">&nbsp;</label><br>
        			<a id="generate-api-btn" class="btn btn-default"><?php echo _('Genereer API key'); ?></a>
        		</div>
        	</div>
        </div>
		
		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
					<label for="debcode" class="control-label">Debiteurcode</label>
                    <input type="text" name="debcode" id="debcode" class="form-control" value="<?php echo $user->getDebcode() ?>" required>
                </div>
        	</div>
        </div>
        
        <div class="row">
        	<div class="col-md-12">
        		<div class="form-group">
            		<div class="checkbox">
            			<label>
            				<input type="checkbox" name="enabled" <?php echo $user->getEnabled() ? 'checked' : '' ?>> Account is ingeschakeld
            			</label>
            		</div>
        		</div>
        	</div>
        </div>
        
        <div class="row">
        	<div class="col-md-12">
        		<div class="form-group">
        			<label class="control-label">Rollen</label>
            		<?php foreach($roles as $role): ?>
            		<div class="checkbox">
            			<label>
            				<input type="checkbox" name="role[<?php echo $role->getRoleId() ?>]" <?php echo $user->getRoles()->contains($role) ? 'checked' : '' ?>> <?php echo $role->getRoleId(); ?>
            			</label>
            		</div>
            		<?php endforeach; ?>
        		</div>
        	</div>
        </div>

        <div class="row">
        	<div class="col-md-12">
        		<div class="form-group">
        			<label class="control-label">Url autorisatie</label>
            		<?php foreach($urls as $url): ?>
            		<div class="checkbox">
            			<label>
            				<input type="checkbox" name="url[<?php echo $url->getId() ?>]" <?php echo $user->getUrls()->contains($url) ? 'checked' : '' ?>> <?php echo $url->getUrlName(); ?>
            			</label>
            		</div>
            		<?php endforeach; ?>
        		</div>
        	</div>
        </div>


		<div class="form-group">
			<button class="btn btn-primary">Opslaan</button>
			<a href="/admin/user" class="btn btn-link">Terug</a>
		</div>


	</form>
</div>

<script>
function generateApiKey() {
	sarr = new Array("abcdefghijkmnopqrstuvwxyz", "ABCDEFGHJKLMNPQRSTUVWXYZ",
			"23456789", "~!@#$%^&*()_+-=\[]{};:,./<>?");
	s = new String();
	pw = new String();
	s = sarr[0] + sarr[1] + sarr[2];
	for (var i = 0; i < 40; i++) {
		pw += s.charAt(Math.floor(Math.random() * s.length));
	}
	$('#apikey').val(pw);
}

$( document ).ready( function() {
	$('#generate-api-btn').click(function(e) {
		generateApiKey();
		
		e.preventDefault();
	});
});

</script>
