<div class="col-md-6 col-md-offset-3">
	<div class="row">
		<h2>Inloggen</h2>
		
		<hr>
	
	</div>

	<form action="/admin/user/login" method="post">
		
		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
					<label for="username" class="control-label">Gebruikersnaam</label>
                    <input type="text" name="username" id="username" class="form-control" required>
                </div>
        	</div>
        </div>
		
		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
					<label for="password" class="control-label">Wachtwoord</label>
					<div class="input-group">
                        <input type="password" name="password" id="password" class="form-control" required>
                        <div class="input-group-addon">
                        	<span id="hideShowPassword" class="glyphicon glyphicon-eye-open"></span>
                        </div>
                    </div>
                </div>
        	</div>
		</div>

		<div class="form-group">
			<button class="btn btn-primary">Inloggen</button>
		</div>
		
	</form>
</div>

<script>
$( document ).ready( function() {
	
	var passField = $('#password');
	
	$('#hideShowPassword').click(function(e) {
		if ($(this).hasClass('glyphicon-eye-open')) {
			$(this).toggleClass('glyphicon-eye-open');
			$(this).toggleClass('glyphicon-eye-close');
			passField.attr('type', 'text');
		} else {
			$(this).toggleClass('glyphicon-eye-close');
			$(this).toggleClass('glyphicon-eye-open');
			passField.attr('type', 'password');
		}
	});
	
});

</script>