<div class="col-md-6 col-md-offset-3">
	<div class="row">
		<h2>Url bewerken</h2>
		
		<hr>
	
	</div>

	<form action="/admin/user" method="post">
		
		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
					<label for="urlName" class="control-label">Naam</label>
                    <input type="text" name="urlName" id="urlName" class="form-control" value="<?php echo $this->url->getUrlName() ?>" required>
                </div>
        	</div>
        </div>

		<div class="form-group">
			<button class="btn btn-primary">Opslaan</button>
			<a href="/admin/url" class="btn btn-link">Terug</a>
		</div>


	</form>
</div>

