<div class="col-md-6 col-md-offset-3">
	<div class="row">
		<h2>Nieuwe url</h2>
		
		<hr>
	
	</div>

	<form action="/admin/role/add" method="post">
		
		<div class="row">
			<div class="col-md-8">
				<div class="form-group">
					<label for="roleId" class="control-label">Naam</label>
                    <input type="text" name="roleId" id="roleId" class="form-control" required>
                </div>
        	</div>
        </div>
		
		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
					<label for="parent" class="control-label">Ouder</label>
                    <select class="form-control" name="parent" id="parent">
                    	<option value="">- Geen -</option>
                    	<?php foreach ($this->parents as $parent) : ?>
                    	<option value="<?php echo $parent->getRoleId(); ?>"><?php echo $parent->getRoleId(); ?></option>
                    	<?php endforeach; ?>
                    </select>
                </div>
        	</div>
        </div>

		<div class="form-group">
			<button class="btn btn-primary">Opslaan</button>
			<a href="/admin/role" class="btn btn-link">Terug</a>
		</div>


	</form>
</div>

