<div class="col-md-6 col-md-offset-3">
	<div class="row">
		<h2>Inloggen</h2>
		
		<hr>
	
	</div>


    <?php
    $form = $this->loginForm;
    $form->prepare();
    $form->setAttribute('action', $this->url('zfcuser/login'));
    $form->setAttribute('method', 'post');
    $form->setAttribute('autocomplete', 'off');
    ?>
    
    <?php echo $this->form()->openTag($form) ?>   
        		
    	<div class="row">
    		<div class="col-md-6">
    			<div class="form-group">
    				<?php $identity = $form->get('identity'); ?>
    				<label for="identity" class="control-label">Gebruikersnaam</label>
                    <input type="text" name="identity" id="identity" class="form-control" required>
                    <span class="help-block">
                    	<strong><?php echo $this->formElementErrors($identity) ?></strong>
                    </span>
                </div>
        	</div>
        </div>
    	
    	<div class="row">
    		<div class="col-md-6">
    			<div class="form-group">
    				<?php $credential = $form->get('credential') ?>
    				<label for="credential" class="control-label">Wachtwoord</label>
    				<div class="input-group">
                        <input type="password" name="credential" id="credential" class="form-control" required>
                        <div class="input-group-addon">
                        	<span id="hideShowPassword" class="glyphicon glyphicon-eye-open"></span>
                        </div>
                    </div>
                    <span class="help-block">
                    	<strong><?php echo $this->formElementErrors($credential) ?></strong>
                    </span>
                </div>
        	</div>
    	</div>
    
    	<div class="form-group">
    		<button class="btn btn-primary">Inloggen</button>
    	</div>
        
    <?php if ($this->redirect) : ?>
        <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>">
    <?php endif ?>
    <?php echo $this->form()->closeTag() ?>
    
    
    
    <?php if ($this->enableRegistration) : ?>
    <?php echo $this->translate('Not registered?'); ?> <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->escapeUrl($this->redirect) : '') ?>"><?php echo $this->translate('Sign up!'); ?></a>
    <?php endif; ?>
</div>

<script>
$( document ).ready( function() {
	
	var passField = $('#credential');
	
	$('#hideShowPassword').click(function(e) {
		if ($(this).hasClass('glyphicon-eye-open')) {
			$(this).toggleClass('glyphicon-eye-open');
			$(this).toggleClass('glyphicon-eye-close');
			passField.attr('type', 'text');
		} else {
			$(this).toggleClass('glyphicon-eye-close');
			$(this).toggleClass('glyphicon-eye-open');
			passField.attr('type', 'password');
		}
	});
	
});

</script>