<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Admin\Module'                        => __DIR__ . '/Module.php',
    'Admin\Controller\AdminController' => __DIR__ . '/src/Admin/Controller/AdminController.php',
    'Admin\Controller\UserController' => __DIR__ . '/src/Admin/Controller/UserController.php',
    'Admin\Controller\UrlController' => __DIR__ . '/src/Admin/Controller/UrlController.php',
    'AdminTest\Framework\TestCase'        => __DIR__ . '/tests/Admin/Framework/TestCase.php',
    'AdminTest\SampleTest'                => __DIR__ . '/tests/Admin/SampleTest.php',
);
