<?= $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
<?php
echo $this->headTitle('De Eekhoorn API');

echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');

echo $this->headLink(['rel' => 'icon', 'type' => 'image/png', 'href' => $this->basePath('/img/favicon.ico')])
    ->prependStylesheet($this->basePath('/zf-apigility/css/main.min.css'))
    ->prependStylesheet($this->basePath('/zf-apigility/css/bootstrap.min.css'));

echo $this->headScript()
    ->prependFile($this->basePath('/zf-apigility/js/bootstrap.min.js'))
    ->prependFile($this->basePath('/zf-apigility/js/jquery.min.js'));
?>
<style>
body {
  padding-top: 60px;
  padding-bottom: 40px;
}
.navbar-default {
  background: #00618B;
}
.navbar-default .navbar-nav > li > a {
  color: #FFF;
  text-shadow: none;
}
.navbar-default .navbar-nav > li > a:hover,
.navbar-default .navbar-nav > li > a:focus {
  color: #FFF;
  background-color: #408AA7;
}
.navbar-default .navbar-nav > .active > a,
.navbar-default .navbar-nav > .active > a:hover,
.navbar-default .navbar-nav > .active > a:focus {
  color: #FFF;
  background: #408AA7;
}
.navbar-default .navbar-nav > .open > a,
.navbar-default .navbar-nav > .open > a:hover,
.navbar-default .navbar-nav > .open > a:focus {
  color: #FFF;
  background-color: #408AA7;
}
.navbar-default .navbar-brand:hover,
.navbar-default .navbar-brand:focus {
  color: #FFF;
  background-color: transparent;
}
div.container a.navbar-brand {
  background: url("/img/Logo_De_Eekhoorn_homepageNW_2.png") no-repeat scroll 0 0 transparent;
  background-size: auto 100%;
  margin-left: 0;
  padding: 14px 20px 12px 200px;
  color: #FFF;
}
.form-standard {
  margin: 0 auto;
  max-width: 640px;
  padding: 15px;
}
.form-login {
  margin: 0 auto;
  max-width: 330px;
  padding: 15px;
}
.form-login .form-control {
  box-sizing: border-box;
  font-size: 16px;
  height: auto;
  padding: 10px;
  position: relative;
}
.panel-success {
	border-color: #00618B;
}
.panel-success > .panel-heading {
	background-color: #408AA7;
	color: #FFF;
	border-color: #00618B;
}
</style>
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->url('home') ?>">API</a>
            </div>
            <div class="collapse navbar-collapse">
            	<?php if ($this->userIdentity()) : ?>
                <ul class="nav navbar-nav">
                    <li><a href="#">Gebruikers</a></li>
                </ul>
                <?php endif; ?>
                <ul class="nav navbar-nav navbar-right">
					<li class="dropdown">
						<?php if ($this->userIdentity()) : ?>
  						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?php echo $this->userIdentity(); ?> <span class="caret"></span></a>
						<?php else: ?>
  						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Mijn Intranet <span class="caret"></span></a>
  						<?php endif; ?>
  						<ul class="dropdown-menu">
  							<?php if ($this->userIdentity()) : ?>
  							
  							<?php else: ?>
    						<li><a href="<?php echo $this->url('pro-user', array('action' => 'login')) ?>">Inloggen</a></li>
    						<?php endif; ?>
  						</ul>
					</li>
  				</ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>

    <div class="container">
        <?= $this->content ?>
    </div>
    <footer>
        <hr>
        <div class="container center-block"><div class="row">
            <div class="col-sm-8">
                &copy; Copyright <?= date('Y') ?>
                by <a href="http://deeekhoorn.com">De Eekhoorn Woodworkings B.V.</a>
            </div>

        </div></div>
    </footer>
    <?= $this->inlineScript() ?>
</body>
</html>
